const proposalPayload = { type:'object', additionalProperties:false, properties:{ age_categories:{type:'array',items:{type:'string'}}, participant_count:{type:['integer','null']}, participants:{type:['string','null']}, result:{type:['string','null']}, observed:{type:['string','null']}, interpreted:{type:['string','null']}, hypothesized:{type:['string','null']}, action:{type:['string','null']}, capacity:{type:['string','null']}, observation:{type:['string','null']}, month_key:{type:['string','null']}, entry_date:{type:['string','null']}, type:{type:['string','null']}, text:{type:['string','null']}, role_ids:{type:'array',items:{type:'string'}} }, required:['age_categories','participant_count','participants','result','observed','interpreted','hypothesized','action','capacity','observation','month_key','entry_date','type','text','role_ids'] };
const provenanceItem = { type:'object', additionalProperties:false, properties:{field:{type:'string'},source:{type:'string',enum:['note','system','becky','missing']},detail:{type:'string'}},required:['field','source','detail']};
const proposal = { type:'object', additionalProperties:false, properties:{ destination:{type:'string',enum:['activity_observation','crm_child_observation','monthly_report_entry','task','content_lab_idea','event_community_finding','knowledge_candidate']}, operation:{type:'string'}, target_candidate:{type:['string','null']}, child_candidates:{type:'array',items:{type:'string'}}, source_excerpt:{type:'string'}, epistemic_type:{type:'string',enum:['observed','interpreted','hypothesized','action','mixed']}, payload:proposalPayload, field_provenance:{type:'array',items:provenanceItem} }, required:['destination','operation','target_candidate','child_candidates','source_excerpt','epistemic_type','payload','field_provenance'] };
const schema = { type:'object', additionalProperties:false, properties:{proposals:{type:'array',maxItems:30,items:proposal}},required:['proposals'] };
export async function analyzeDailyNoteWithOpenAI({ apiKey, model = 'gpt-4.1-mini', noteDate, noteText, children, activities, roles }) {
  if (!apiKey) throw Object.assign(new Error('OPENAI_API_KEY lipsește'), { status:503 });
  const response = await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model,instructions:`Analizezi o Notă zilnică Becky și propui mutații atomice pentru review uman. Nu scrii nimic canonic. Separă strict observed, interpreted, hypothesized și action. Nu inventa ID-uri, persoane, activități, vârste, rezultate sau roluri. target_candidate conține doar numele/titlul menționat, niciodată ID. Creează Activity Observation numai dacă este numită o activitate concretă. CRM Child Observation conține exclusiv un fapt observat sau o afirmație directă a copilului, niciodată interpretări/profilare. Monthly Report Entry evită date personale inutile. Pentru V1 propune doar activity_observation/add, crm_child_observation/add și monthly_report_entry/add; celelalte destinații sunt permise de schemă dar nu le folosi. Pentru result poți propune o valoare canonică doar dacă este explicită sau susținută clar; marchează becky dacă este inferență. Valorile canonice: participants Individual|2–3 copii|4–9 copii|10+ copii; result A mers bine|Mixt|Nu a mers; ages 1–2 ani|3–4 ani|5–6 ani|7–8 ani|9+ ani; monthly type done|evidence|learned; role_ids exclusiv din lista primită. Câmpurile necunoscute rămân null, [] sau text gol și provenance missing. O singură experiență poate produce propuneri distincte către destinații diferite.`,input:JSON.stringify({note_date:noteDate,note:noteText,canonical_context:{children:children.map(child=>({name:child.first_name,age:child.age})),activities:activities.map(activity=>({title:activity.title,age_categories:activity.age_categories})),roles}}),text:{format:{type:'json_schema',name:'becky_inbox_proposals',strict:true,schema}}})});
  const result=await response.json().catch(()=>({})); const outputText=result.output?.flatMap(item=>item.content||[]).find(item=>item.type==='output_text')?.text;
  if(!response.ok||!outputText)throw Object.assign(new Error(response.status===429?'Limita OpenAI a fost atinsă.':'Nota nu a putut fi analizată.'),{status:response.status===429?429:502});
  return JSON.parse(outputText).proposals||[];
}
