alter table public.admin_experience_repertoire_items
  add column if not exists family text,
  add column if not exists fallback_item_id uuid references public.admin_experience_repertoire_items(id) on delete set null;

create table if not exists public.admin_experience_repertoire_age_overlays (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.admin_experience_repertoire_items(id) on delete cascade,
  age_group text not null check (age_group in ('age_2','age_3','age_4_5','age_6_7','age_8_plus')),
  validation_status text not null default 'idea' check (validation_status in ('idea','validated')),
  age_specific_note text,
  restriction text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (item_id, age_group)
);

create index if not exists admin_experience_repertoire_age_overlays_item_idx
  on public.admin_experience_repertoire_age_overlays(item_id);

insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('11111111-1111-4111-8111-111111111111','welcome','Dăm noroc','O invitație simplă la strângere de mână ca prim gest de conectare.',array['age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('11111111-1111-4111-8111-111111111111','age_6_7','idea','În repertoriul actual este folosit mai ales pentru băieți de 6+ ani; nu este o regulă universală de gen.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('11111111-1111-4111-8111-111111111111','age_8_plus','idea','În repertoriul actual este folosit mai ales pentru băieți de 6+ ani; nu este o regulă universală de gen.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('22222222-2222-4222-8222-222222222222','welcome','Batem palma','Invit copilul la un high-five ca prim gest simplu și jucăuș de conectare, fără să insist dacă nu răspunde.',array['age_2','age_3','age_4_5','age_6_7','age_8_plus'],'active',null,'33333333-3333-4333-8333-333333333333') on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('22222222-2222-4222-8222-222222222222','age_2','idea','Gest scurt și opțional; dacă nu răspunde, coborâm presiunea interacțiunii.','Nu insistăm cu contact fizic dacă nu răspunde.') on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('22222222-2222-4222-8222-222222222222','age_3','idea','Gest scurt și opțional; dacă nu răspunde, coborâm presiunea interacțiunii.','Nu insistăm cu contact fizic dacă nu răspunde.') on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('22222222-2222-4222-8222-222222222222','age_4_5','idea','Gest scurt și opțional; dacă nu răspunde, coborâm presiunea interacțiunii.','Nu insistăm cu contact fizic dacă nu răspunde.') on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('22222222-2222-4222-8222-222222222222','age_6_7','idea','Gest scurt și opțional; dacă nu răspunde, coborâm presiunea interacțiunii.','Nu insistăm cu contact fizic dacă nu răspunde.') on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('22222222-2222-4222-8222-222222222222','age_8_plus','idea','Gest scurt și opțional; dacă nu răspunde, coborâm presiunea interacțiunii.','Nu insistăm cu contact fizic dacă nu răspunde.') on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('33333333-3333-4333-8333-333333333333','welcome','Observ & remarc','Observ ceva concret pe care copilul îl poartă, îl ține sau îl urmărește și fac o remarcă prietenoasă, fără să cer un răspuns.',array['age_2','age_3','age_4_5','age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('33333333-3333-4333-8333-333333333333','age_2','idea','Exemplu: «Văd că ai venit cu un dinozaur.»',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('33333333-3333-4333-8333-333333333333','age_3','idea','Exemplu: «Ce șapcă mișto ai.»',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('33333333-3333-4333-8333-333333333333','age_4_5','idea','Exemplu: «Ce șapcă mișto ai.»',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('33333333-3333-4333-8333-333333333333','age_6_7','idea','Exemplu: «Văd că ai venit cu un dinozaur.»',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('33333333-3333-4333-8333-333333333333','age_8_plus','idea','Exemplu: «Văd că ai venit cu un dinozaur.»',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('44444444-4444-4444-8444-444444444444','surprise_connect','Banul din nas','Folosesc trucul ca mic moment de surpriză și conectare.',array['age_4_5','age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('44444444-4444-4444-8444-444444444444','age_4_5','idea',null,'Nu pentru copii sub 4 ani: copilul mic poate interpreta trucul literal și poate încerca ulterior să introducă un obiect în nas.') on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('44444444-4444-4444-8444-444444444444','age_6_7','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('44444444-4444-4444-8444-444444444444','age_8_plus','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('55555555-5555-4555-8555-555555555555','surprise_connect','Bureții care apar în mână','Truc de magie în care bureții apar în mâna copilului, folosit ca moment scurt de surpriză și conectare.',array['age_4_5','age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('55555555-5555-4555-8555-555555555555','age_4_5','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('55555555-5555-4555-8555-555555555555','age_6_7','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('55555555-5555-4555-8555-555555555555','age_8_plus','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('66666666-6666-4666-8666-666666666666','surprise_connect','Baloane de săpun','Folosesc câteva baloane de săpun ca moment neașteptat de conectare, adaptând interacțiunea la vârsta copilului.',array['age_2','age_3','age_4_5','age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('66666666-6666-4666-8666-666666666666','age_2','idea','Surpriză vizuală simplă. Fac baloanele și las copilul să le urmărească sau să le spargă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('66666666-6666-4666-8666-666666666666','age_3','idea','Similar cu 2 ani, dar pot introduce o interacțiune foarte simplă în jurul lor.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('66666666-6666-4666-8666-666666666666','age_4_5','idea','Introduc puțin joc: «Prinzi unul?» / «Câte reușești să spargi?»',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('66666666-6666-4666-8666-666666666666','age_6_7','idea','Transform rapid momentul într-o provocare scurtă: «Poți să spargi trei dintr-o singură mișcare?»',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('66666666-6666-4666-8666-666666666666','age_8_plus','idea','Folosesc ideea doar dacă găsesc un unghi suficient de provocator sau amuzant încât să nu pară infantil.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('77777777-7777-4777-8777-777777777777','next_visit_thread','Țin minte ce îți place','Pornesc de la un personaj, univers, animal, temă sau alt interes pe care am descoperit că îl pasionează pe copil și îi spun că data viitoare îi pregătesc ceva legat de acel interes. Exemplu: «Știu că îți place Stitch. Data viitoare îți pregătesc eu ceva cu Stitch.»',array['age_2','age_3','age_4_5','age_6_7','age_8_plus'],'active','emotional_interest',null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('77777777-7777-4777-8777-777777777777','age_2','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('77777777-7777-4777-8777-777777777777','age_3','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('77777777-7777-4777-8777-777777777777','age_4_5','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('77777777-7777-4777-8777-777777777777','age_6_7','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('77777777-7777-4777-8777-777777777777','age_8_plus','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('88888888-8888-4888-8888-888888888888','next_visit_thread','Ridică ștacheta','Dacă am descoperit o abilitate sau o mișcare fizică care îi place copilului, propun ca la vizita următoare să încercăm ceva nou sau puțin mai dificil. Exemple: «Data viitoare învățăm încă două mișcări.» / «Data viitoare încercăm un salt nou.»',array['age_4_5','age_6_7','age_8_plus'],'active','motor',null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('88888888-8888-4888-8888-888888888888','age_4_5','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('88888888-8888-4888-8888-888888888888','age_6_7','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('88888888-8888-4888-8888-888888888888','age_8_plus','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('99999999-9999-4999-8999-999999999999','next_visit_thread','Următorul nivel','Dacă unui copil i-a plăcut să rezolve o provocare, îi spun că data viitoare îi voi pregăti una asemănătoare, dar nouă sau puțin mai dificilă. Exemplu: «Data viitoare îți pregătesc una și mai grea.»',array['age_4_5','age_6_7','age_8_plus'],'active','cognitive',null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('99999999-9999-4999-8999-999999999999','age_4_5','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('99999999-9999-4999-8999-999999999999','age_6_7','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('99999999-9999-4999-8999-999999999999','age_8_plus','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','next_visit_thread','Continuăm și adăugăm ceva nou','Continuăm sau evoluăm ceva creat împreună — construcție, desen, poveste, proiect — ideal introducând la vizita următoare un element nou și neașteptat. Exemple: «Data viitoare continuăm construcția, dar eu vin cu ceva nou pentru ea.» / «Data viitoare facem partea a doua.»',array['age_3','age_4_5','age_6_7','age_8_plus'],'active','creative',null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','age_3','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','age_4_5','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','age_6_7','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','age_8_plus','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','memorable_close','Cadoul Becky','Ofer copilului cadoul Becky atunci când ajunge la a treia vizită.',array['age_2','age_3','age_4_5','age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','age_2','idea','Regula actuală este vizita a 3-a.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','age_3','idea','Regula actuală este vizita a 3-a.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','age_4_5','idea','Regula actuală este vizita a 3-a.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','age_6_7','idea','Regula actuală este vizita a 3-a.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','age_8_plus','idea','Regula actuală este vizita a 3-a.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','memorable_close','Îi spun ce am învățat despre el','La final îi spun copilului ceva concret ce am observat sau am învățat despre el ori despre interesele lui. Exemple: «Acum știu că tu ești omul cu dinozaurii.» / «Am văzut că nu te lași până nu îți iese.»',array['age_2','age_3','age_4_5','age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','age_2','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','age_3','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','age_4_5','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','age_6_7','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','age_8_plus','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','memorable_close','Salutul Becky','Dacă am avut timp să îl învățăm în timpul vizitei, încheiem folosind Salutul Becky ca ritual comun.',array['age_2','age_3','age_4_5','age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','age_2','idea','Fără variante noi inventate; folosesc ritualul existent unde este rezonabil.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','age_3','idea','Fără variante noi inventate; folosesc ritualul existent unde este rezonabil.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','age_4_5','idea','Fără variante noi inventate; folosesc ritualul existent unde este rezonabil.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','age_6_7','idea','Fără variante noi inventate; folosesc ritualul existent unde este rezonabil.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','age_8_plus','idea','Fără variante noi inventate; folosesc ritualul existent unde este rezonabil.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','memorable_close','Îi spun ce mi-a plăcut la cum a făcut ceva','Marchez ceva concret din comportamentul sau efortul copilului din vizita respectivă, nu laudă generică. Exemplu: «Mi-a plăcut că ai încercat de trei ori până ți-a ieșit.»',array['age_2','age_3','age_4_5','age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','age_2','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','age_3','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','age_4_5','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','age_6_7','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','age_8_plus','idea','Adaptez limbajul la vârstă.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('ffffffff-ffff-4fff-8fff-ffffffffffff','memorable_close','Ce ai făcut rămâne aici','Dacă situația permite, păstrăm o urmă a lucrului creat sau făcut de copil: expunem creația, păstrăm construcția pentru data viitoare sau marcăm într-un mod vizibil că acel lucru îi aparține.',array['age_3','age_4_5','age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('ffffffff-ffff-4fff-8fff-ffffffffffff','age_3','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('ffffffff-ffff-4fff-8fff-ffffffffffff','age_4_5','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('ffffffff-ffff-4fff-8fff-ffffffffffff','age_6_7','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('ffffffff-ffff-4fff-8fff-ffffffffffff','age_8_plus','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('12121212-1212-4121-8121-121212121212','memorable_close','Ritualul nostru','Construiesc în timp un mic element comun cu copilul — gest, parolă amuzantă, replică sau handshake — care poate fi reluat la vizitele următoare.',array['age_4_5','age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('12121212-1212-4121-8121-121212121212','age_4_5','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('12121212-1212-4121-8121-121212121212','age_6_7','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('12121212-1212-4121-8121-121212121212','age_8_plus','idea',null,null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_items (id,stage,title,description,age_groups,status,family,fallback_item_id) values ('13131313-1313-4131-8131-131313131313','memorable_close','Surpriză finală','Închei vizita, când este potrivit, cu un mic moment neașteptat de «wow»: balon modelat, truc de magie potrivit vârstei, mini-moment cu baloane de săpun sau un mic obiect-surpriză dacă există ceva potrivit. Nu este obligatoriu la fiecare vizită.',array['age_2','age_3','age_4_5','age_6_7','age_8_plus'],'active',null,null) on conflict (id) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('13131313-1313-4131-8131-131313131313','age_2','idea','Variantele concrete trebuie să respecte restricțiile lor de vârstă; nu combin cu Cadoul Becky de la vizita 3.','Nu folosesc trucuri sau obiecte care pot fi interpretate literal și introduse în nas.') on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('13131313-1313-4131-8131-131313131313','age_3','idea','Variantele concrete trebuie să respecte restricțiile lor de vârstă; nu combin cu Cadoul Becky de la vizita 3.','Nu folosesc trucuri sau obiecte care pot fi interpretate literal și introduse în nas.') on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('13131313-1313-4131-8131-131313131313','age_4_5','idea','Variantele concrete trebuie să respecte restricțiile lor de vârstă; nu combin cu Cadoul Becky de la vizita 3.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('13131313-1313-4131-8131-131313131313','age_6_7','idea','Variantele concrete trebuie să respecte restricțiile lor de vârstă; nu combin cu Cadoul Becky de la vizita 3.',null) on conflict (item_id,age_group) do nothing;
insert into public.admin_experience_repertoire_age_overlays (item_id,age_group,validation_status,age_specific_note,restriction) values ('13131313-1313-4131-8131-131313131313','age_8_plus','idea','Variantele concrete trebuie să respecte restricțiile lor de vârstă; nu combin cu Cadoul Becky de la vizita 3.',null) on conflict (item_id,age_group) do nothing;
update public.admin_experience_repertoire_items set fallback_item_id = '22222222-2222-4222-8222-222222222222' where id = '11111111-1111-4111-8111-111111111111';
update public.admin_experience_repertoire_items set fallback_item_id = '33333333-3333-4333-8333-333333333333' where id = '22222222-2222-4222-8222-222222222222';
