const signal = {type:'object',additionalProperties:false,properties:{exact_source_excerpt:{type:'string'},normalized_observation:{type:'string'},epistemic_type:{type:'string',enum:['observed','direct_quote','activity_evidence','action_intent']},entities:{type:'object',additionalProperties:false,properties:{children:{type:'array',items:{type:'string'}},activities:{type:'array',items:{type:'string'}}},required:['children','activities']},topics:{type:'array',items:{type:'string'}},age_categories:{type:'array',items:{type:'string'}},confidence:{type:'number',minimum:0,maximum:1}},required:['exact_source_excerpt','normalized_observation','epistemic_type','entities','topics','age_categories','confidence']};
const attention = {type:'object',additionalProperties:false,properties:{title:{type:'string'},summary:{type:'string'},why_it_matters:{type:'string'},suggested_next_step:{type:'string'},evidence_refs:{type:'array',items:{type:'string'}},counter_evidence_refs:{type:'array',items:{type:'string'}},topics:{type:'array',items:{type:'string'}},age_categories:{type:'array',items:{type:'string'}},relevance_score:{type:'number',minimum:0,maximum:100},confidence:{type:'number',minimum:0,maximum:1}},required:['title','summary','why_it_matters','suggested_next_step','evidence_refs','counter_evidence_refs','topics','age_categories','relevance_score','confidence']};
const schema={type:'object',additionalProperties:false,properties:{memory_signals:{type:'array',maxItems:40,items:signal},attention_candidates:{type:'array',maxItems:8,items:attention}},required:['memory_signals','attention_candidates']};

export async function analyzeDailyNoteForMemory({ apiKey, model='gpt-4.1-mini', noteDate, noteText, children, activities, historicContext }) {
  if(!apiKey)throw Object.assign(new Error('OPENAI_API_KEY lipsește'),{status:503});
  const instructions=`Organizezi memoria Becky după o Notă zilnică. Nu scrii direct în taskuri, knowledge candidates, activități sau alte concluzii canonice. Returnezi două liste: memory_signals și attention_candidates. Un memory signal poate fi: observed/direct_quote/activity_evidence pentru fapte, SAU action_intent pentru o intenție explicită, un gol de sistem sau un lucru concret pe care autorul spune că trebuie să-l construiască/verifice/planifice. Pentru action_intent păstrează formularea ca intenție, nu o prezenta ca fapt împlinit. exact_source_excerpt trebuie copiat identic din nota curentă. normalized_observation formulează concis aceeași informație. Nu scrii «este timid», «are nevoie», «probabil» sau alte interpretări ca signal factual. IMPORTANT: «consider că», «cred că», «probabil», «ar aprecia», «ar putea», «mi se pare» și «presupun» sunt ipoteze/interpretări; nu le include ca observed. O intenție explicită precum «îmi lipsesc elemente pentru fiecare categorie de vârstă» sau «trebuie să am un plan clar» poate fi action_intent și merită păstrată chiar dintr-o singură notă. Entity names pot fi doar nume/titluri menționate în notă; nu inventa ID-uri. Pentru attention_candidates, ZERO este valid pentru observații banale. Poți crea un candidat și dintr-un singur fragment atunci când există o intenție strategică clară, un gol important sau un plan concret care cere următorul pas; nu crea candidate pentru orice fapt. evidence_refs și counter_evidence_refs conțin exclusiv fragmente exacte din notă sau din memory_context.memory_signals. Un candidat trebuie să fie mai valoros decât evidence-ul brut: să schimbe o decizie, să formuleze un plan sau un test concret.`;
  const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model,instructions,input:JSON.stringify({note_date:noteDate,note:noteText,canonical_context:{children:children.map(child=>({name:child.first_name,age:child.age})),activities:activities.map(activity=>({title:activity.title,age_categories:activity.age_categories}))},memory_context:historicContext}),text:{format:{type:'json_schema',name:'becky_memory_analysis',strict:true,schema}}})});
  const result=await response.json().catch(()=>({}));const outputText=result.output?.flatMap(item=>item.content||[]).find(item=>item.type==='output_text')?.text;
  if(!response.ok||!outputText)throw Object.assign(new Error(response.status===429?'Limita OpenAI a fost atinsă.':'Nota nu a putut fi analizată.'),{status:response.status===429?429:502});
  const parsed=JSON.parse(outputText);return {memory_signals:parsed.memory_signals||[],attention_candidates:parsed.attention_candidates||[]};
}
